### ISSUE TITLE
Errors with FES 2.3.1

### ISSUE THREAD

**Issue by brashrebel** [Astoundify/edd-fes-product-details#11]
I believe these errors are related to some changes in the latest version of FES which was released this week. When using the widget and setting a couple fields on the submission form to "Show this data separately on the product listing page." including a File Upload field, the following errors are shown:

```
Notice: Undefined index: input_type in /Users/kylemaurer/Documents/Websites/edd.dev/wp-content/plugins/easy-digital-downloads-frontend-submissions-product-details-widget/widget.php on line 111

Notice: Undefined index: is_meta in /Users/kylemaurer/Documents/Websites/edd.dev/wp-content/plugins/easy-digital-downloads-frontend-submissions-product-details-widget/widget.php on line 170

Warning: preg_split() expects parameter 2 to be string, array given in /Users/kylemaurer/Documents/Websites/edd.dev/wp-includes/formatting.php on line 2118

Warning: Invalid argument supplied for foreach() in /Users/kylemaurer/Documents/Websites/edd.dev/wp-includes/formatting.php on line 2120
```

I spent a little time experimenting with `widget.php` and found some things but no final resolution. I am confused by [this line](https://github.com/Astoundify/edd-fes-product-details/blob/master/widget.php#L121) which sets `$value` to a string and subsequently checks to see if it is an array. Anyway, let me know if I can help in anyway.

**Comment by spencerfinnell** [comment]
Heh, no idea! I'll try to take a look soon.
